{% set version = "0.1.5" %}

package:
  name: confection
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/confection/confection-{{ version }}.tar.gz
  sha256: 8e72dd3ca6bd4f48913cd220f10b8275978e740411654b6e8ca6d7008c590f0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.6
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0
    - typing_extensions >=3.7.4.1,<5.0.0
    - srsly >=2.4.0,<3.0.0

test:
  imports:
    - confection
  requires:
    - pytest
    - numpy
    - pip
  commands:
    - python -m pytest --tb=native --pyargs confection
    - pip check


about:
  home: https://github.com/explosion/confection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The sweetest config system for Python
  description: |
    A lightweight library that offers a configuration system letting you
    conveniently describe arbitrary trees of objects.
  doc_url: https://github.com/explosion/confection
  dev_url: https://github.com/explosion/confection

extra:
  recipe-maintainers:
    - conda-forge/spacy
