{% set version = "1.1.0" %}

package:
  name: confection
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/confection/confection-{{ version }}.tar.gz
  sha256: 01de6b5d755e551565935f9efd37eb496826ba1e7c20ed89cc0248e8b3bfd2ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - confection
  requires:
    - python {{ python_min }}
    - pytest
    - hypothesis
    - numpy
    - pip
    - catalogue >=2.0.3,<2.1.0
    - pydantic >=1.7.4,<3.0.0
    - pathy >=0.3.5
  commands:
    - python -m pytest --tb=native --pyargs confection
    - pip check


about:
  home: https://github.com/explosion/confection
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The sweetest config system for Python
  description: |
    A lightweight library that offers a configuration system letting you
    conveniently describe arbitrary trees of objects.
  doc_url: https://github.com/explosion/confection
  dev_url: https://github.com/explosion/confection

extra:
  recipe-maintainers:
    - conda-forge/spacy
